const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Clipboard,
		C3.Plugins.HTMLElement,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetName,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLogin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Clipboard.Cnds.OnCopySuccess,
		C3.Plugins.Button.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Якорь: 0},
	{Picsart_250611_: 0},
	{Прикрепить: 0},
	{Autorizen: 0},
	{Create_Pay: 0},
	{NickName: 0},
	{GamePush: 0},
	{GamePushChannels: 0},
	{Balane_txt: 0},
	{Твинанимация: 0},
	{Fon_Menu: 0},
	{Profile_Button: 0},
	{Тач: 0},
	{Close_Menu: 0},
	{ID_txt: 0},
	{NickName_txt: 0},
	{Profile_Button2: 0},
	{БуферОбмена: 0},
	{SecretCode_Button: 0},
	{Text: 0},
	{Info_Button2: 0},
	{Loading_gid: 0},
	{Close_Info: 0},
	{HTMLЭлемент: 0}
];

self.InstanceType = {
	Picsart_250611_: class extends self.ISpriteInstance {},
	Autorizen: class extends self.IButtonInstance {},
	Create_Pay: class extends self.IButtonInstance {},
	NickName: class extends self.ITextInputInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	GamePushChannels: class extends self.C3.Plugins.GamePush_Channels.Instance {},
	Balane_txt: class extends self.ITextInstance {},
	Fon_Menu: class extends self.ITiledBackgroundInstance {},
	Profile_Button: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Close_Menu: class extends self.ISpriteInstance {},
	ID_txt: class extends self.ITextInstance {},
	NickName_txt: class extends self.ITextInstance {},
	Profile_Button2: class extends self.ISpriteInstance {},
	БуферОбмена: class extends self.IInstance {},
	SecretCode_Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Info_Button2: class extends self.IButtonInstance {},
	Loading_gid: class extends self.ISpriteInstance {},
	Close_Info: class extends self.ISpriteInstance {},
	HTMLЭлемент: class extends self.IHTMLElementInstance {}
}